services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:rocm
    volumes:
      - ./volumes/ollama:/root/.ollama
      - ./volumes/model-files:/mnt/model-files
    ports:
      - "11434:11434"
    devices:
      - /dev/dri
      - /dev/kfd
    restart: unless-stopped


  open-terminal:
    image: ghcr.io/open-webui/open-terminal:latest
    container_name: open-terminal
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/files:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=""