services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:rocm
    volumes:
      - ./volumes/ollama:/root/.ollama
      - ./volumes/model-files:/mnt/model-files
    ports:
      - "11434:11434"
    devices:
      - /dev/dri
      - /dev/kfd
    restart: unless-stopped